# Generated by Django 4.2.20 on 2025-07-28 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario_coleta_escolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo_caminhao', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('bairro', models.CharField(max_length=100)),
                ('motorista_nome', models.CharField(max_length=100)),
                ('motorista_matricula', models.CharField(max_length=50)),
                ('coletor_nome', models.CharField(max_length=100)),
                ('coletor_matricula', models.CharField(max_length=50)),
                ('horario_chegada', models.TimeField()),
                ('horario_saida', models.TimeField()),
                ('bag_plastico', models.PositiveIntegerField(default=0)),
                ('bag_papel', models.PositiveIntegerField(default=0)),
                ('bag_aluminio', models.PositiveIntegerField(default=0)),
                ('bag_eletronico', models.PositiveIntegerField(default=0)),
                ('bag_vazio', models.PositiveIntegerField(default=0)),
                ('bag_semi_cheio', models.PositiveIntegerField(default=0)),
                ('bag_cheio', models.PositiveIntegerField(default=0)),
                ('assinatura_responsavel', models.CharField(max_length=200)),
                ('telefone_responsavel', models.CharField(max_length=20)),
                ('cpf_responsavel', models.CharField(max_length=14)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coletas', to='escola.escola')),
            ],
        ),
    ]
