# Generated by Django 4.2.20 on 2025-07-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='questionario_coleta_escolar',
            index=models.Index(fields=['bag_plastico', 'bag_papel', 'bag_aluminio', 'bag_eletronico', 'bag_vazio', 'bag_semi_cheio', 'bag_cheio'], name='questionari_bag_pla_acb50d_idx'),
        ),
        migrations.AddIndex(
            model_name='questionario_coleta_escolar',
            index=models.Index(fields=['escola'], name='questionari_escola__4845e0_idx'),
        ),
    ]
