# Generated by Django 4.2.20 on 2025-07-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['nome_escola'], name='escola_esco_nome_es_012ca2_idx')],
            },
        ),
    ]
